### ISSUE TITLE
Cannot read properties of null (reading 'id')

### ISSUE THREAD

**Issue by websuits** [Myrmod/vitejs-theming#1]
I'm coming from your tutorial and i would like to understand how this works but i can't understand this issue.
Can you give a little hint on this one ? 

7:59:04 PM [vite] Internal server error: Cannot read properties of null (reading 'id')
      at /Users/me/workspace/test/testify/vite.config.js:41:93
      at Array.find (<anonymous>)
      at Context.resolveId (/Users/me/workspace/test/testify/vite.config.js:41:41)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Object.resolveId (/Users/me/workspace/test/testify/node_modules/vite/dist/node/chunks/dep-8f5c9290.js:39229:32)
      at async ModuleGraph.resolveUrl (/Users/me/workspace/test/testify/node_modules/vite/dist/node/chunks/dep-8f5c9290.js:58920:26)
      at async ModuleGraph.getModuleByUrl (/Users/me/workspace/test/testify/node_modules/vite/dist/node/chunks/dep-8f5c9290.js:58800:23)
      at async doTransform (/Users/me/workspace/test/testify/node_modules/vite/dist/node/chunks/dep-8f5c9290.js:49932:20) (x2)

**Comment by Myrmod** [comment]
Is your code public and could you share it please?

**Comment by websuits** [comment]
Here is my repo : https://github.com/websuits/magstartify
 
yarn; yarn dev
node v16.15.0

Thanks for looking into it, can't seem to find anything related on the entire internet. I'm pretty noob at vitejs and i'm still figuring it how to debug it.

**Comment by Myrmod** [comment]
The problem lies in `build-plugins/rollup/replace-files.js:17`

replace it with 

```js
const foundReplace = replacements.find((replacement) => {
        console.log(replacement, resolved);
        return replacement.find === resolved?.id;
      });
```
And you will see how the paths are being resolved.

As far as I can tell it is not working as expected in your project. You can get rid of the error using the code above. However you might need to adjust the condition to your needs.

The code could look like this:

```js
const foundReplace = replacements.find(
        (replacement) => resolved?.id && resolved.id.includes(replacement.find),
      );
```

**Comment by Myrmod** [comment]
Almost seems to me like the SSR is not playing nice with the file replacements for some reason

You're not using `https://github.com/Myrmod/vitejs-theming/blob/master/build-plugins/generateAliases.js`

This function exists to correctly resolve the file paths. In there you can see the `path.resolve` calls. They're important to prevent errors.

**Comment by websuits** [comment]
@Myrmod You are right, generateAliases fixes the SSR issue.

I just need to figure out why it's loading App.tsx instead of App.server.tsx now. ( Nailed it meanwhile )

Thank you !
